source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'BannerExample' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationAdColony'
  pod 'GoogleMobileAdsMediationUnity'
  pod 'GoogleMobileAdsMediationTestSuite'
  pod 'GoogleMobileAdsMediationVungle'
end
