source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'RewardedVideoExample' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK-EAP', :podspec => 'Google-Mobile-Ads-SDK-EAP.podspec.json'
  pod 'GoogleMobileAdsMediationAdColony'
  pod 'GoogleMobileAdsMediationUnity'

end
