source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'RewardedVideoExample' do
  pod 'Google-Mobile-Ads-SDK-EAP', :podspec => 'Google-Mobile-Ads-SDK-EAP.podspec.json'
  pod 'GoogleMobileAdsMediationAdColony'
  pod 'GoogleMobileAdsMediationUnity'
end
